//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalificacionesAlumnos {
	
	
	public partial class Index {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Repeater RepetidorAlumnos;
		
		protected System.Web.UI.WebControls.Label StudentName;
		
		protected System.Web.UI.WebControls.TextBox StudentNote;

        protected System.Web.UI.WebControls.Literal TextPromedio;

        protected System.Web.UI.WebControls.Literal TextMinimo;

        protected System.Web.UI.WebControls.Literal TextMaximo;

        protected System.Web.UI.WebControls.Literal TextModa;
    }
}
